version: 2.1

parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

orbs: 
  aws-cli: circleci/aws-cli@3.1.4
jobs: 
  aws-cli-cred-setup: 
    executor: aws-cli/default
    steps: 
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
workflows: 
  branch-created: 
    when: 
      equal: [ "create", << pipeline.parameters.GHA_Event >>] 
    jobs: 
      - aws-cli-cred-setup:
          context: aws
  branch-deleted: 
    when: 
      equal: [ "delete", << pipeline.parameters.GHA_Event >>] 
    jobs: 
      - aws-cli-cred-setup:
          context: aws
