on: 
  [create,delete]
jobs: 
  trigger-circleci:
    runs-on: ubuntu-latest
    steps: 
      - name: branch_event
        id: be
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env: 
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
