on: 
  create
jobs: 
  trigger-circleci:
    runs-on: ubuntu:latest
    steps: 
      - name: branch_created
        id: bc
        uses: circleci/trigger_circleci_pipeline@v1.0
        env: 
        CCI_TOKEN: $
